#!/bin/bash

# Quick bash script to look up the current bitcoin exchange rate for CNY and
# USD and convert between bitcoin and real currency

# http://www.coindesk.com/api/
# Alternative: https://blockchain.info/api/exchange_rates_api
curr_rate=$(curl "http://api.coindesk.com/v1/bpi/currentprice/CNY.json" 2>/dev/null)
cny_rate=$(jq ".bpi.CNY.rate_float" <<<"$curr_rate")
usd_rate=$(jq ".bpi.USD.rate_float" <<<"$curr_rate")
curr_time=$(jq ".time.updatedISO" <<<"$curr_rate")

title="Most recent:"

cat <<EOF
CURRENT BTC EXCHANGE RATE
=== $(sed -e 's/T/ /g' -e 's/"//g' <<<${curr_time%+*}) UTC ===
========== CNY ==========
  ${title} ${cny_rate}

========== USD ==========
  ${title} ${usd_rate}

EOF

while true; do
  read -p "Select a conversion
  1. BTC to RMB
  2. RMB to BTC
  3. BTC to USD
  4. USD to BTC
  (Enter q to quit, default 1): " conv_type

  [ -z "$conv_type" ] && conv_type=1
  [ "$conv_type" = "q" ] && exit 0

  read -p "Amount: " amount

  case "$conv_type" in
    1)
      res=$(bc <<<"scale=2; ${amount} * ${cny_rate}") ;;
    2)
      res=$(printf "%0.7f\n" $(bc <<<"scale=7; ${amount} / ${cny_rate}")) ;;
    3)
      res=$(bc <<<"scale=2; ${amount} * ${usd_rate}") ;;
    4)
      res=$(printf "%0.7f\n" $(bc <<<"scale=7; ${amount} / ${usd_rate}")) ;;
    *)
      echo "Unsupported option. Exit"
      exit 1 ;;
  esac

  echo -e "Result: ${res}\n"
done
